apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-openshift-machineconfig-master-dummy-networks
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Create dummy network
          After=NetworkManager.service
          
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/nmcli conn add type dummy ifname eth10 autoconnect yes save yes con-name internalEtcd ip4 192.168.126.11/24
          
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: dummy-network.service
    networkd: {}
    passwd: {}
    storage: {}
    osImageURL: ""

